import {
  LucideBot,
  LucideCircle,
  LucideClipboard,
  LucideCloud,
  LucideCodeXml,
  LucideCopy,
  LucideDatabase,
  LucideDownload,
  LucideDroplets,
  LucideEye,
  LucideEyeOff,
  LucideFolder,
  LucideFolderOpen,
  LucideGauge,
  LucideGlobe,
  LucideHand,
  LucideHistory,
  LucideInfo,
  LucideLoaderCircle,
  LucideLocateFixed,
  LucideMail,
  LucideMapPinned,
  LucideMinus,
  LucideMoon,
  LucideMousePointer2,
  LucideMove,
  LucidePanelLeft,
  LucidePanelRight,
  LucidePencil,
  LucidePentagon,
  LucidePlay,
  LucideRefreshCcw,
  LucideRotateCcw,
  LucideRuler,
  LucideSave,
  LucideScanSearch,
  LucideSearch,
  LucideSettings,
  LucideSlash,
  LucideSparkles,
  LucideSquareDashed,
  LucideSquareTerminal,
  LucideSun,
  LucideTable,
  LucideTrash2,
  LucideUpload,
  LucideX,
  LucideIconData,
  provideLucideIcons
} from '@lucide/angular';

const LucideGithub: LucideIconData = {
  name: 'github',
  node: [
    ['circle', { cx: 12, cy: 12, r: 9 }],
    ['path', { d: 'M9 18v-2.4c-2 .5-2.5-1-2.5-1' }],
    ['path', { d: 'M15 18v-3.2c0-.8-.3-1.3-.8-1.7 2.4-.3 4.8-1.1 4.8-5A3.9 3.9 0 0 0 18 5.4c.1-.3.4-1.4-.1-2.7 0 0-.9-.3-2.8 1a9.5 9.5 0 0 0-5.2 0c-1.9-1.3-2.8-1-2.8-1-.5 1.3-.2 2.4-.1 2.7A3.9 3.9 0 0 0 6 8.1c0 3.9 2.4 4.7 4.8 5-.5.4-.8 1-.8 1.9V18' }]
  ]
};

const LucideLinkedin: LucideIconData = {
  name: 'linkedin',
  node: [
    ['rect', { x: 4, y: 4, width: 16, height: 16, rx: 2 }],
    ['path', { d: 'M8 10v6' }],
    ['path', { d: 'M8 8h.01' }],
    ['path', { d: 'M12 16v-6' }],
    ['path', { d: 'M12 12.6c.5-1 1.3-1.6 2.4-1.6 1.7 0 2.6 1.1 2.6 3.2V16' }]
  ]
};

export const provideMappiaLucideIcons = () =>
  provideLucideIcons(
    LucideBot,
    LucideCircle,
    LucideClipboard,
    LucideCloud,
    LucideCodeXml,
    LucideCopy,
    LucideDatabase,
    LucideDownload,
    LucideDroplets,
    LucideEye,
    LucideEyeOff,
    LucideFolder,
    LucideFolderOpen,
    LucideGauge,
    LucideGithub,
    LucideGlobe,
    LucideHand,
    LucideHistory,
    LucideInfo,
    LucideLinkedin,
    LucideLoaderCircle,
    LucideLocateFixed,
    LucideMail,
    LucideMapPinned,
    LucideMinus,
    LucideMoon,
    LucideMousePointer2,
    LucideMove,
    LucidePanelLeft,
    LucidePanelRight,
    LucidePencil,
    LucidePentagon,
    LucidePlay,
    LucideRefreshCcw,
    LucideRotateCcw,
    LucideRuler,
    LucideSave,
    LucideScanSearch,
    LucideSearch,
    LucideSettings,
    LucideSlash,
    LucideSparkles,
    LucideSquareDashed,
    LucideSquareTerminal,
    LucideSun,
    LucideTable,
    LucideTrash2,
    LucideUpload,
    LucideX
  );
